# Generated by Django 4.0.5 on 2023-01-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deputado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('partido', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=50)),
                ('regiao', models.CharField(max_length=127)),
                ('cargo', models.CharField(max_length=50)),
                ('curriculo', models.TextField(max_length=40000)),
                ('carreira', models.TextField(max_length=40000)),
                ('biografia', models.TextField(max_length=40000)),
                ('papel', models.CharField(max_length=127)),
            ],
        ),
    ]
