# Generated by Django 4.0.5 on 2023-01-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislatura56', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deputado',
            name='cargo',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='deputado',
            name='estado',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='deputado',
            name='nome',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='deputado',
            name='papel',
            field=models.CharField(max_length=40000),
        ),
        migrations.AlterField(
            model_name='deputado',
            name='partido',
            field=models.CharField(max_length=50),
        ),
    ]
